apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files (x86)\kompose\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: dhbw-seminarbeit-eventbus
  name: dhbw-seminarbeit-eventbus
spec:
  ports:
  - name: "4005"
    port: 4005
    targetPort: 4005
  selector:
    io.kompose.service: dhbw-seminarbeit-eventbus
status:
  loadBalancer: {}
