apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: dhbw-seminarbeit-eventbus
  name: dhbw-seminarbeit-eventbus
spec:
  type: NodePort
  ports:
  - name: "4005"
    port: 4005
    targetPort: 4005
  selector:
    app.kubernetes.io/name: dhbw-seminarbeit-eventbus
status:
  loadBalancer: {}
