apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: dhbw-seminarbeit-eventbus
  name: dhbw-seminarbeit-eventbus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dhbw-seminarbeit-eventbus
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dhbw-seminarbeit-eventbus
    spec:
      containers:
      - env:
        - name: DISPLAYDATA_ENDPOINT
          valueFrom:
            configMapKeyRef:
              key: DISPLAYDATA_ENDPOINT
              name: dhbw-seminararbeit-displaydata-env
        image: flo101/dhbw-seminarbeit-eventbus
        imagePullPolicy: ""
        name: dhbw-seminarbeit-eventbus
        ports:
        - containerPort: 4005
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
